services:
  postgres:
    image: postgres:16-alpine
    container_name: monapp-postgres1
    restart: unless-stopped
    environment:
      POSTGRES_DB: monapp
      POSTGRES_USER: monapp
      POSTGRES_PASSWORD: monapp
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: axelmengue1/monapp-backend:1.0.0
    container_name: monapp-backend1
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monapp
      SPRING_DATASOURCE_USERNAME: monapp
      SPRING_DATASOURCE_PASSWORD: monapp
    ports:
      - "8080:8080"

  frontend:
    image: axelmengue1/monapp-frontend:1.0.0
    container_name: monapp-frontend1
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data1: