CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_brands_nom_lower ON brands (LOWER(nom));

INSERT INTO brands (nom, created_at, updated_at)
SELECT DISTINCT TRIM(marque), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM products
WHERE marque IS NOT NULL AND TRIM(marque) <> '';

ALTER TABLE products ADD COLUMN marque_id BIGINT;
ALTER TABLE products ADD CONSTRAINT fk_products_brand FOREIGN KEY (marque_id) REFERENCES brands (id);

UPDATE products
SET marque_id = (
    SELECT b.id FROM brands b
    WHERE LOWER(TRIM(b.nom)) = LOWER(TRIM(products.marque))
    FETCH FIRST 1 ROW ONLY
)
WHERE marque IS NOT NULL AND TRIM(marque) <> '';

ALTER TABLE products DROP COLUMN marque;
