ALTER TABLE supplier_purchase_orders ADD COLUMN IF NOT EXISTS notes VARCHAR(1000);
ALTER TABLE supplier_purchase_orders ADD COLUMN IF NOT EXISTS warehouse_id BIGINT;
ALTER TABLE supplier_purchase_orders ADD COLUMN IF NOT EXISTS stock_entry_id BIGINT;
ALTER TABLE supplier_purchase_orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS supplier_purchase_order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    variant_id BIGINT,
    quantity DECIMAL(19, 6) NOT NULL,
    received_quantity DECIMAL(19, 6) NOT NULL DEFAULT 0,
    unit_price DECIMAL(19, 4),
    notes VARCHAR(500),
    CONSTRAINT fk_po_line_order FOREIGN KEY (purchase_order_id) REFERENCES supplier_purchase_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_po_line_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_po_line_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id)
);

INSERT INTO supplier_purchase_order_lines (purchase_order_id, product_id, quantity, received_quantity)
SELECT id, product_id, 1, 0
FROM supplier_purchase_orders
WHERE product_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM supplier_purchase_order_lines l WHERE l.purchase_order_id = supplier_purchase_orders.id
  );

ALTER TABLE supplier_purchase_orders DROP CONSTRAINT IF EXISTS supplier_purchase_orders_status_check;
ALTER TABLE supplier_purchase_orders ADD CONSTRAINT supplier_purchase_orders_status_check
    CHECK (status IN ('PENDING', 'PARTIALLY_RECEIVED', 'DELIVERED', 'CANCELLED'));
