-- Valorisation stock CMP (Coût Moyen Pondéré) — état courant + historique

CREATE TABLE IF NOT EXISTS stock_valuation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    variant_id BIGINT,
    quantity_on_hand NUMERIC(19, 6) NOT NULL DEFAULT 0,
    stock_value NUMERIC(19, 6) NOT NULL DEFAULT 0,
    average_unit_cost NUMERIC(19, 6) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_valuation_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_stock_valuation_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_stock_valuation_product_variant
    ON stock_valuation (product_id, COALESCE(variant_id, 0));

CREATE INDEX IF NOT EXISTS idx_stock_valuation_product ON stock_valuation (product_id);

CREATE TABLE IF NOT EXISTS stock_valuation_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    variant_id BIGINT,
    movement_type VARCHAR(32) NOT NULL,
    movement_date TIMESTAMP NOT NULL,
    quantity NUMERIC(19, 6) NOT NULL,
    unit_cost NUMERIC(19, 6) NOT NULL,
    total_value NUMERIC(19, 6) NOT NULL,
    average_unit_cost_after NUMERIC(19, 6) NOT NULL,
    stock_quantity_after NUMERIC(19, 6) NOT NULL,
    stock_value_after NUMERIC(19, 6) NOT NULL,
    source_id BIGINT,
    source_type VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_svm_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_svm_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id),
    CONSTRAINT chk_svm_movement_type CHECK (
        movement_type IN ('PURCHASE', 'SALE', 'RETURN', 'ADJUSTMENT', 'INVENTORY')
    )
);

CREATE INDEX IF NOT EXISTS idx_svm_product_date ON stock_valuation_movements (product_id, movement_date);
CREATE INDEX IF NOT EXISTS idx_svm_variant_date ON stock_valuation_movements (variant_id, movement_date);
CREATE INDEX IF NOT EXISTS idx_svm_movement_date ON stock_valuation_movements (movement_date);

ALTER TABLE sale_lines
    ADD COLUMN IF NOT EXISTS unit_cost_at_sale NUMERIC(19, 6);
