CREATE TABLE IF NOT EXISTS stock_entry_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_entry_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_stock_entry_attachment_entry FOREIGN KEY (stock_entry_id)
        REFERENCES stock_entries (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_stock_entry_attachments_entry ON stock_entry_attachments (stock_entry_id);
