CREATE TABLE IF NOT EXISTS user_favorite_nav_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    nav_item_key VARCHAR(60) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_favorite_nav_item_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_favorite_nav_item UNIQUE (user_id, nav_item_key)
);

CREATE INDEX IF NOT EXISTS idx_user_favorite_nav_items_user ON user_favorite_nav_items (user_id);
