CREATE TABLE IF NOT EXISTS sale_exchanges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange_number VARCHAR(50) NOT NULL,
    original_sale_id BIGINT NOT NULL,
    refund_id BIGINT NOT NULL,
    new_sale_id BIGINT NOT NULL,
    net_amount NUMERIC(19,4) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_sale_exchange_number UNIQUE (exchange_number),
    CONSTRAINT fk_sale_exchange_original_sale FOREIGN KEY (original_sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sale_exchange_refund FOREIGN KEY (refund_id) REFERENCES sale_refunds (id),
    CONSTRAINT fk_sale_exchange_new_sale FOREIGN KEY (new_sale_id) REFERENCES sales (id)
);

CREATE INDEX IF NOT EXISTS idx_sale_exchanges_original_sale ON sale_exchanges (original_sale_id);
