-- Retours / remboursements POS : enrichissement sale_refunds + refund_payments

ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS cashier_id bigint;
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS pos_session_id bigint;
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS customer_id bigint;
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS refund_status character varying(30);
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS notes character varying(500);
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS validated_at timestamp(6) with time zone;
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS cancelled_at timestamp(6) with time zone;
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS manager_validated_by character varying(120);
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS manager_validated_at timestamp(6) with time zone;

UPDATE sale_refunds SET refund_status = 'REFUNDED'
WHERE refund_status IS NULL AND status = 'COMPLETED';

UPDATE sale_refunds SET refund_status = 'PENDING'
WHERE refund_status IS NULL;

UPDATE sale_refunds SET validated_at = completed_at
WHERE validated_at IS NULL AND status = 'COMPLETED';

ALTER TABLE sale_refunds ALTER COLUMN refund_status SET DEFAULT 'PENDING';

DO $$ BEGIN
    ALTER TABLE sale_refunds ADD CONSTRAINT fk_sale_refunds_cashier
        FOREIGN KEY (cashier_id) REFERENCES users (id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE sale_refunds ADD CONSTRAINT fk_sale_refunds_pos_session
        FOREIGN KEY (pos_session_id) REFERENCES pos_sessions (id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE sale_refunds ADD CONSTRAINT fk_sale_refunds_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS product_id bigint;
ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS packaging_id bigint;
ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS packaging_name_snapshot character varying(255);
ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS packaging_quantity_snapshot numeric(19,6);
ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS quantity_in_base_unit numeric(19,6);
ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS unit_price_snapshot numeric(19,4);
ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS restock boolean;
ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS reason character varying(500);
ALTER TABLE sale_refund_lines ADD COLUMN IF NOT EXISTS notes character varying(500);

UPDATE sale_refund_lines srl
SET restock = sr.return_to_stock,
    quantity_in_base_unit = srl.quantity,
    unit_price_snapshot = sl.unit_price_snapshot,
    packaging_id = sl.packaging_id,
    packaging_name_snapshot = sl.packaging_name_snapshot,
    packaging_quantity_snapshot = sl.packaging_quantity_snapshot,
    product_id = sl.product_id
FROM sale_refunds sr,
     sale_lines sl
WHERE srl.refund_id = sr.id
  AND sl.id = srl.sale_line_id
  AND srl.restock IS NULL;

UPDATE sale_refund_lines SET restock = true WHERE restock IS NULL;
UPDATE sale_refund_lines SET quantity_in_base_unit = quantity WHERE quantity_in_base_unit IS NULL;

DO $$ BEGIN
    ALTER TABLE sale_refund_lines ADD CONSTRAINT fk_sale_refund_lines_product
        FOREIGN KEY (product_id) REFERENCES products (id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE sale_refund_lines ADD CONSTRAINT fk_sale_refund_lines_packaging
        FOREIGN KEY (packaging_id) REFERENCES product_packagings (id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS refund_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_refund_id bigint NOT NULL,
    original_payment_id bigint,
    cashier_id bigint NOT NULL,
    pos_session_id bigint NOT NULL,
    method character varying(30) NOT NULL,
    amount numeric(19,4) NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'REFUNDED',
    refunded_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_refund_payments_refund FOREIGN KEY (sale_refund_id) REFERENCES sale_refunds (id),
    CONSTRAINT fk_refund_payments_original FOREIGN KEY (original_payment_id) REFERENCES payments (id),
    CONSTRAINT fk_refund_payments_cashier FOREIGN KEY (cashier_id) REFERENCES users (id),
    CONSTRAINT fk_refund_payments_session FOREIGN KEY (pos_session_id) REFERENCES pos_sessions (id),
    CONSTRAINT refund_payments_method_check CHECK (method IN ('CASH','CARD','MOBILE_MONEY','BANK_TRANSFER','OTHER')),
    CONSTRAINT refund_payments_status_check CHECK (status IN ('PENDING','REFUNDED','FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_refund_payments_session ON refund_payments (pos_session_id);
CREATE INDEX IF NOT EXISTS idx_refund_payments_refund ON refund_payments (sale_refund_id);
CREATE INDEX IF NOT EXISTS idx_sale_refunds_sale ON sale_refunds (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_refunds_session ON sale_refunds (pos_session_id);
