-- Attributs de variante dynamiques + is_sellable + packaging par variante

ALTER TABLE products ADD COLUMN IF NOT EXISTS is_sellable boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS variant_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(120) NOT NULL,
    code character varying(50) NOT NULL,
    description character varying(500),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uk_variant_attributes_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS variant_attribute_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_id bigint NOT NULL,
    attr_value character varying(120) NOT NULL,
    code character varying(50),
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_variant_attr_values_attribute FOREIGN KEY (attribute_id) REFERENCES variant_attributes (id),
    CONSTRAINT uk_variant_attr_values UNIQUE (attribute_id, attr_value)
);

CREATE INDEX IF NOT EXISTS idx_variant_attr_values_attribute ON variant_attribute_values (attribute_id);

CREATE TABLE IF NOT EXISTS product_variant_attribute_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id bigint NOT NULL,
    attribute_id bigint NOT NULL,
    attribute_value_id bigint NOT NULL,
    CONSTRAINT fk_pvav_variant FOREIGN KEY (product_variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
    CONSTRAINT fk_pvav_attribute FOREIGN KEY (attribute_id) REFERENCES variant_attributes (id),
    CONSTRAINT fk_pvav_value FOREIGN KEY (attribute_value_id) REFERENCES variant_attribute_values (id),
    CONSTRAINT uk_pvav_variant_attribute UNIQUE (product_variant_id, attribute_id)
);

CREATE INDEX IF NOT EXISTS idx_pvav_variant ON product_variant_attribute_values (product_variant_id);
CREATE INDEX IF NOT EXISTS idx_pvav_value ON product_variant_attribute_values (attribute_value_id);

ALTER TABLE product_packagings ADD COLUMN IF NOT EXISTS variant_id bigint;
DO $$ BEGIN
    ALTER TABLE product_packagings ADD CONSTRAINT fk_product_packagings_variant
        FOREIGN KEY (variant_id) REFERENCES product_variants (id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Attributs système Couleur / Taille
INSERT INTO variant_attributes (name, code, description, is_active)
VALUES ('Couleur', 'COULEUR', 'Attribut variante couleur', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO variant_attributes (name, code, description, is_active)
VALUES ('Taille', 'TAILLE', 'Attribut variante taille', true)
ON CONFLICT (code) DO NOTHING;

-- Migration couleur existante
INSERT INTO variant_attribute_values (attribute_id, attr_value, code, sort_order, is_active)
SELECT va.id, v.couleur, UPPER(REGEXP_REPLACE(v.couleur, '[^A-Za-z0-9]+', '', 'g')), 0, true
FROM (
    SELECT DISTINCT TRIM(couleur) AS couleur
    FROM product_variants
    WHERE couleur IS NOT NULL AND TRIM(couleur) <> ''
) v
JOIN variant_attributes va ON va.code = 'COULEUR'
ON CONFLICT (attribute_id, attr_value) DO NOTHING;

-- Migration taille existante
INSERT INTO variant_attribute_values (attribute_id, attr_value, code, sort_order, is_active)
SELECT va.id, v.taille, UPPER(REGEXP_REPLACE(v.taille, '[^A-Za-z0-9]+', '', 'g')), 0, true
FROM (
    SELECT DISTINCT TRIM(taille) AS taille
    FROM product_variants
    WHERE taille IS NOT NULL AND TRIM(taille) <> ''
) v
JOIN variant_attributes va ON va.code = 'TAILLE'
ON CONFLICT (attribute_id, attr_value) DO NOTHING;

-- Liaisons variante ↔ valeurs (couleur)
INSERT INTO product_variant_attribute_values (product_variant_id, attribute_id, attribute_value_id)
SELECT pv.id, va.id, val.id
FROM product_variants pv
JOIN variant_attributes va ON va.code = 'COULEUR'
JOIN variant_attribute_values val ON val.attribute_id = va.id AND val.attr_value = TRIM(pv.couleur)
WHERE pv.couleur IS NOT NULL AND TRIM(pv.couleur) <> ''
ON CONFLICT (product_variant_id, attribute_id) DO NOTHING;

-- Liaisons variante ↔ valeurs (taille)
INSERT INTO product_variant_attribute_values (product_variant_id, attribute_id, attribute_value_id)
SELECT pv.id, va.id, val.id
FROM product_variants pv
JOIN variant_attributes va ON va.code = 'TAILLE'
JOIN variant_attribute_values val ON val.attribute_id = va.id AND val.attr_value = TRIM(pv.taille)
WHERE pv.taille IS NOT NULL AND TRIM(pv.taille) <> ''
ON CONFLICT (product_variant_id, attribute_id) DO NOTHING;

-- Produits avec variantes : parent non vendable directement
UPDATE products p
SET is_sellable = false
WHERE EXISTS (SELECT 1 FROM product_variants pv WHERE pv.product_id = p.id);
