package com.erp.products.domain.enums;

public enum AuditAction {
    CREATION,
    MODIFICATION,
    SUPPRESSION,
    CHANGEMENT_PRIX,
    CHANGEMENT_CATEGORIE,
    CHANGEMENT_STATUT,
    CHANGEMENT_CYCLE_VIE,
    AJOUT_VARIANTE,
    SUPPRESSION_VARIANTE,
    AJOUT_FOURNISSEUR,
    SUPPRESSION_FOURNISSEUR,
    AJOUT_IMAGE,
    SUPPRESSION_IMAGE,
    AJOUT_DOCUMENT,
    SUPPRESSION_DOCUMENT
}
